In [2]:
import numpy as np

In [7]:
A = np.ones(3, dtype=int) - np.eye(3, dtype=int)
A

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [8]:
A_squared = A@A
A_squared

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [9]:
np.sum(A_squared * A)

np.int64(6)

In [10]:
A_squared * A

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [11]:
6 * 3 ** 3

162

In [7]:
%pip install sympy


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [12]:
import sympy

F163 = sympy.GF(163)

In [13]:
x1, x2, y1, y2 = sympy.symbols('x1, x2, y1, y2')

In [23]:
def idx_to_expr(idx: int, s1, s2):
    assert idx >= 0 and idx < 4

    expr = 1
    if idx & 2:
        expr *= s1
    else:
        expr *= (1 - s1)

    if idx & 1:
        expr *= s2
    else:
        expr *= (1 - s2)

    return expr

def matrix_to_poly(a: np.array, field):
    assert len(a.shape) == 2
    n, m = a.shape
    assert n == m and n <= 4
    e = 0
    
    for i in range(n):
        for j in range(n):
            subexpr = a[i][j] * idx_to_expr(i, x1, x2) * idx_to_expr(j, y1, y2)
            # print(f"{i},{j}: {subexpr}")
            e += subexpr

    return e.as_poly(domain=field)

def eval_matrix_poly_at(poly, i: int, j: int):
    return poly.eval({x1: i & 2 > 0, x2: i & 1, y1: j & 2 > 0, y2: j & 1})

def pretty_print_poly_evals(poly, n=4):
    for i in range(n):
        for j in range(n):
            print(eval_matrix_poly_at(poly, i, j), end=' ')
        print()

In [24]:
p_A = matrix_to_poly(A, F163)
p_A

Poly(-2*x1*x2*y1*y2 + 2*x1*x2*y1 + 2*x1*x2*y2 - 2*x1*x2 + 2*x1*y1*y2 - 2*x1*y1 - x1*y2 + x1 + 2*x2*y1*y2 - x2*y1 - 2*x2*y2 + x2 - 2*y1*y2 + y1 + y2, x1, x2, y1, y2, modulus=163)

In [78]:
p_A.eval({x1: 0, x2: 0, y1: 0, y2: 0})

0

In [79]:
p_A.eval({x1: 0, x2: 0, y1: 1, y2: 0})

1

In [25]:
pretty_print_poly_evals(p_A, n = 3)

0 1 1 
1 0 1 
1 1 0 


In [27]:
p_A2 = matrix_to_poly(A_squared, F163)
pretty_print_poly_evals(p_A2,n=3)

2 1 1 
1 2 1 
1 1 2 


In [28]:
print(sympy.latex(p_A))
print(sympy.latex(p_A2))

\operatorname{Poly}{\left( -2 x_{1}x_{2}y_{1}y_{2} + 2 x_{1}x_{2}y_{1} + 2 x_{1}x_{2}y_{2} - 2 x_{1}x_{2} + 2 x_{1}y_{1}y_{2} - 2 x_{1}y_{1} - x_{1}y_{2} + x_{1} + 2 x_{2}y_{1}y_{2} - x_{2}y_{1} - 2 x_{2}y_{2} + x_{2} - 2 y_{1}y_{2} + y_{1} + y_{2}, x_{1}, x_{2}, y_{1}, y_{2}, domain=\mathbb{F}_{163} \right)}
\operatorname{Poly}{\left( 4 x_{1}x_{2}y_{1}y_{2} - 2 x_{1}x_{2}y_{1} - 2 x_{1}x_{2}y_{2} - 2 x_{1}y_{1}y_{2} + 2 x_{1}y_{1} + x_{1}y_{2} - x_{1} - 2 x_{2}y_{1}y_{2} + x_{2}y_{1} + 2 x_{2}y_{2} - x_{2} - y_{1} - y_{2} + 2, x_{1}, x_{2}, y_{1}, y_{2}, domain=\mathbb{F}_{163} \right)}
