In [1]:
import numpy as np

In [2]:
A = np.array([
 [0,1,1,0],
 [1,0,1,1],
 [1,1,0,1],
 [0,1,1,0],
])

In [3]:
A_squared = A@A
A_squared

array([[2, 1, 1, 2],
       [1, 3, 2, 1],
       [1, 2, 3, 1],
       [2, 1, 1, 2]])

In [4]:
np.sum(A_squared * A)

np.int64(12)

In [5]:
A_squared * A

array([[0, 1, 1, 0],
       [1, 0, 2, 1],
       [1, 2, 0, 1],
       [0, 1, 1, 0]])

In [6]:
6 * 4 ** 3

384

In [7]:
%pip install sympy


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [23]:
import sympy

F389 = sympy.GF(389)

In [24]:
x1, x2, y1, y2 = sympy.symbols('x1, x2, y1, y2')

In [25]:
e = (1 - x1) * x2
e

x2*(1 - x1)

In [26]:
e.as_poly(domain=F389)

Poly(-x1*x2 + x2, x1, x2, modulus=389)

In [27]:
e += 390 * y1
e

x2*(1 - x1) + 390*y1

In [28]:
e.as_poly(domain=domain)

Poly(-x1*x2 + x2 + y1, x1, x2, y1, modulus=389)

In [35]:
e = F389(0)
e

SymmetricModularIntegerMod389(0)

In [36]:
e += x1
e

x1

In [76]:
def idx_to_expr(idx: int, s1, s2):
    assert idx >= 0 and idx < 4

    expr = 1
    if idx & 2:
        expr *= s1
    else:
        expr *= (1 - s1)

    if idx & 1:
        expr *= s2
    else:
        expr *= (1 - s2)

    return expr

def matrix_to_poly(a: np.array, field):
    assert a.shape == (4,4)
    e = 0
    
    for i in range(4):
        for j in range(4):
            subexpr = a[i][j] * idx_to_expr(i, x1, x2) * idx_to_expr(j, y1, y2)
            # print(f"{i},{j}: {subexpr}")
            e += subexpr

    return e.as_poly(domain=field)

def eval_matrix_poly_at(poly, i: int, j: int):
    return poly.eval({x1: i & 2 > 0, x2: i & 1, y1: j & 2 > 0, y2: j & 1})

def pretty_print_poly_evals(poly):
    for i in range(4):
        for j in range(4):
            print(eval_matrix_poly_at(poly, i, j), end=' ')
        print()

In [77]:
p_A = matrix_to_poly(A, F389)
p_A

Poly(-6*x1*x2*y1*y2 + 3*x1*x2*y1 + 3*x1*x2*y2 - 2*x1*x2 + 3*x1*y1*y2 - 2*x1*y1 - x1*y2 + x1 + 3*x2*y1*y2 - x2*y1 - 2*x2*y2 + x2 - 2*y1*y2 + y1 + y2, x1, x2, y1, y2, modulus=389)

In [78]:
p_A.eval({x1: 0, x2: 0, y1: 0, y2: 0})

0

In [79]:
p_A.eval({x1: 0, x2: 0, y1: 1, y2: 0})

1

In [82]:
pretty_print_poly_evals(p_A)

0 1 1 0 
1 0 1 1 
1 1 0 1 
0 1 1 0 
Poly(-6*x1*x2*y1*y2 + 3*x1*x2*y1 + 3*x1*x2*y2 - 2*x1*x2 + 3*x1*y1*y2 - 2*x1*y1 - x1*y2 + x1 + 3*x2*y1*y2 - x2*y1 - 2*x2*y2 + x2 - 2*y1*y2 + y1 + y2, x1, x2, y1, y2, modulus=389)


In [81]:
p_A2 = matrix_to_poly(A_squared, F389)
pretty_print_poly_evals(p_A2)

2 1 1 2 
1 3 2 1 
1 2 3 1 
2 1 1 2 


In [84]:
print(sympy.latex(p_A))
print(sympy.latex(p_A2))

\operatorname{Poly}{\left( -6 x_{1}x_{2}y_{1}y_{2} + 3 x_{1}x_{2}y_{1} + 3 x_{1}x_{2}y_{2} - 2 x_{1}x_{2} + 3 x_{1}y_{1}y_{2} - 2 x_{1}y_{1} - x_{1}y_{2} + x_{1} + 3 x_{2}y_{1}y_{2} - x_{2}y_{1} - 2 x_{2}y_{2} + x_{2} - 2 y_{1}y_{2} + y_{1} + y_{2}, x_{1}, x_{2}, y_{1}, y_{2}, domain=\mathbb{F}_{389} \right)}
\operatorname{Poly}{\left( 10 x_{1}x_{2}y_{1}y_{2} - 5 x_{1}x_{2}y_{1} - 5 x_{1}x_{2}y_{2} + 2 x_{1}x_{2} - 5 x_{1}y_{1}y_{2} + 3 x_{1}y_{1} + 2 x_{1}y_{2} - x_{1} - 5 x_{2}y_{1}y_{2} + 2 x_{2}y_{1} + 3 x_{2}y_{2} - x_{2} + 2 y_{1}y_{2} - y_{1} - y_{2} + 2, x_{1}, x_{2}, y_{1}, y_{2}, domain=\mathbb{F}_{389} \right)}


In [85]:
p_combined = p_A * p_A2
p_combined

Poly(-60*x1**2*x2**2*y1**2*y2**2 + 60*x1**2*x2**2*y1**2*y2 - 15*x1**2*x2**2*y1**2 + 60*x1**2*x2**2*y1*y2**2 - 62*x1**2*x2**2*y1*y2 + 16*x1**2*x2**2*y1 - 15*x1**2*x2**2*y2**2 + 16*x1**2*x2**2*y2 - 4*x1**2*x2**2 + 60*x1**2*x2*y1**2*y2**2 - 68*x1**2*x2*y1**2*y2 + 19*x1**2*x2*y1**2 - 52*x1**2*x2*y1*y2**2 + 62*x1**2*x2*y1*y2 - 18*x1**2*x2*y1 + 11*x1**2*x2*y2**2 - 14*x1**2*x2*y2 + 4*x1**2*x2 - 15*x1**2*y1**2*y2**2 + 19*x1**2*y1**2*y2 - 6*x1**2*y1**2 + 11*x1**2*y1*y2**2 - 15*x1**2*y1*y2 + 5*x1**2*y1 - 2*x1**2*y2**2 + 3*x1**2*y2 - x1**2 + 60*x1*x2**2*y1**2*y2**2 - 52*x1*x2**2*y1**2*y2 + 11*x1*x2**2*y1**2 - 68*x1*x2**2*y1*y2**2 + 62*x1*x2**2*y1*y2 - 14*x1*x2**2*y1 + 19*x1*x2**2*y2**2 - 18*x1*x2**2*y2 + 4*x1*x2**2 - 62*x1*x2*y1**2*y2**2 + 62*x1*x2*y1**2*y2 - 15*x1*x2*y1**2 + 62*x1*x2*y1*y2**2 - 68*x1*x2*y1*y2 + 18*x1*x2*y1 - 15*x1*x2*y2**2 + 18*x1*x2*y2 - 6*x1*x2 + 16*x1*y1**2*y2**2 - 18*x1*y1**2*y2 + 5*x1*y1**2 - 14*x1*y1*y2**2 + 18*x1*y1*y2 - 6*x1*y1 + 3*x1*y2**2 - 4*x1*y2 + 2*x1 - 15*x2**2*y1

In [99]:
print(sympy.latex(p_combined))

\operatorname{Poly}{\left( -60 x_{1}^{2}x_{2}^{2}y_{1}^{2}y_{2}^{2} + 60 x_{1}^{2}x_{2}^{2}y_{1}^{2}y_{2} - 15 x_{1}^{2}x_{2}^{2}y_{1}^{2} + 60 x_{1}^{2}x_{2}^{2}y_{1}y_{2}^{2} - 62 x_{1}^{2}x_{2}^{2}y_{1}y_{2} + 16 x_{1}^{2}x_{2}^{2}y_{1} - 15 x_{1}^{2}x_{2}^{2}y_{2}^{2} + 16 x_{1}^{2}x_{2}^{2}y_{2} - 4 x_{1}^{2}x_{2}^{2} + 60 x_{1}^{2}x_{2}y_{1}^{2}y_{2}^{2} - 68 x_{1}^{2}x_{2}y_{1}^{2}y_{2} + 19 x_{1}^{2}x_{2}y_{1}^{2} - 52 x_{1}^{2}x_{2}y_{1}y_{2}^{2} + 62 x_{1}^{2}x_{2}y_{1}y_{2} - 18 x_{1}^{2}x_{2}y_{1} + 11 x_{1}^{2}x_{2}y_{2}^{2} - 14 x_{1}^{2}x_{2}y_{2} + 4 x_{1}^{2}x_{2} - 15 x_{1}^{2}y_{1}^{2}y_{2}^{2} + 19 x_{1}^{2}y_{1}^{2}y_{2} - 6 x_{1}^{2}y_{1}^{2} + 11 x_{1}^{2}y_{1}y_{2}^{2} - 15 x_{1}^{2}y_{1}y_{2} + 5 x_{1}^{2}y_{1} - 2 x_{1}^{2}y_{2}^{2} + 3 x_{1}^{2}y_{2} - x_{1}^{2} + 60 x_{1}x_{2}^{2}y_{1}^{2}y_{2}^{2} - 52 x_{1}x_{2}^{2}y_{1}^{2}y_{2} + 11 x_{1}x_{2}^{2}y_{1}^{2} - 68 x_{1}x_{2}^{2}y_{1}y_{2}^{2} + 62 x_{1}x_{2}^{2}y_{1}y_{2} - 14 x_{1}x_{2}^{2}y_{1} + 19 x_{1}

In [86]:
sum(eval_matrix_poly_at(p_combined, i,j) for i in range(4) for j in range(4))

12

In [91]:
def latex_print_matrix(a: np.array):
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            print(a[i][j], end = ' ')
            if j != a.shape[1] - 1:
                print("&", end=' ')
        if i != a.shape[0] - 1:
            print(' \\\\')

In [93]:
latex_print_matrix(A_squared)

2 & 1 & 1 & 2  \\
1 & 3 & 2 & 1  \\
1 & 2 & 3 & 1  \\
2 & 1 & 1 & 2 

In [95]:
bla = lambda a: sum(a[i][j] * a[j][k] * a[k][i] for i in range(4) for j in range(4) for k in range(4))
bla(A)

np.int64(12)

In [97]:
A3 = A @ A @ A
A3.trace()

np.int64(12)

In [101]:
A * A_squared

array([[0, 1, 1, 0],
       [1, 0, 2, 1],
       [1, 2, 0, 1],
       [0, 1, 1, 0]])

In [102]:
latex_print_matrix(A * A_squared)

0 & 1 & 1 & 0  \\
1 & 0 & 2 & 1  \\
1 & 2 & 0 & 1  \\
0 & 1 & 1 & 0 