In [1]:
import numpy as np

In [45]:
p = 23
plot = np.zeros((p, p), dtype=int)
plot

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [46]:
for t in range(p):
    x, y = ((t+2) % p, (4 - 2*t) % p)
    plot[x,y] = 1

plot

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0

In [53]:
# for i in range(p-1, -1, -1):
for j in range(p-1, -1, -1):
    print(f"{j}", end='\t')
    for i in range(p):
        if i == 2 and j == 4:
            print("\x1b[34;1m" "b" "\x1b[0m", end='  ')
        elif i == 3 and j == 2:
            print("\x1b[34;1m" "c" "\x1b[0m", end='  ')
        elif plot[i,j] == 1:
            # print("X", end='  ')
            print("\x1b[31;1m" "#" "\x1b[0m", end='  ')
        else:
            print(".", end='  ')
    print()
print("  ", end='\t')
for j in range(p):
    print(j, end=(3-len(str(j)))*' ')


22	.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  #  .  .  .  .  .  .  
21	.  .  .  .  .  #  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
20	.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  #  .  .  .  .  .  
19	.  .  .  .  .  .  #  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
18	.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  #  .  .  .  .  
17	.  .  .  .  .  .  .  #  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
16	.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  #  .  .  .  
15	.  .  .  .  .  .  .  .  #  .  .  .  .  .  .  .  .  .  .  .  .  .  .  
14	.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  #  .  .  
13	.  .  .  .  .  .  .  .  .  #  .  .  .  .  .  .  .  .  .  .  .  .  .  
12	.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  #  .  
11	.  .  .  .  .  .  .  .  .  .  #  .  .  .  .  .  .  .  .  .  .  .  .  
10	.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  #  
9	.  .  .  .  .  .  .  .  .  .  .  #  .  .  .  .  .

In [56]:

def order2_line(point1, point2, point3):
    x = np.array([point1[0], point2[0], point3[0]])
    y = np.array([point1[1], point2[1], point3[1]])

    A = np.array([
        [0, 0, 1],
        [1, 1, 1],
        [4, 2, 1],
    ])

    return np.linalg.solve(A, x), np.linalg.solve(A, y)

In [57]:
order2_line([0,1], [2,2], [8,5])

(array([2., 0., 0.]), array([1., 0., 1.]))

In [60]:
order2_line([1,1], [2,3], [3,9])

(array([0., 1., 1.]), array([2., 0., 1.]))

In [61]:
order2_line([1,1], [5, 3], [9, 17])

(array([0., 4., 1.]), array([ 6., -4.,  1.]))

In [62]:
(4 * 15 + 1 ) % 29

3

In [71]:
order2_line([2, 2], [5, 7], [16, 14])

(array([ 4., -1.,  2.]), array([1., 4., 2.]))